### ISSUE TITLE
amd4j fails to resolve paths if plugin prefix is present

### ISSUE THREAD

**Issue by jknack** [jknack/amd4j#4]
Given:

``` js
define(['cache!ckeditor']..
```

with

```
ckeditor=empty:
```

Amd4j throws a file not found error:

```
Caused by: com.github.jknack.amd4j.AmdException: Execution of: groupFilesPage.page resulted in exception:
 groupFilesPage.page
  foldersView
    entryItemView
      activity
        wallPostActivityView
          activityView
            wallInput
              walleditor
                cache!ckeditor
```

As a workaround you need to add:

```
cache!ckeditor=empty:
```

**Comment by erktime** [comment]
This workaround isn't working for me.

I get something along the lines of:

```
Caused by: java.io.FileNotFoundException: /require-cache
    at com.github.jknack.amd4j.Amd4j.resolve(Amd4j.java:237) ~[amd4j-core-0.1.0.jar:na]
    at com.github.jknack.amd4j.Amd4j.walk(Amd4j.java:178) ~[amd4j-core-0.1.0.jar:na]
    ... 78 common frames omitted
```

I think you want to load the cache plugin, but you don't want to have that plugin attempt to do anything...
